def downgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    columns = inspector.get_columns("variable")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("variable", schema=None) as batch_op:
        name_column = [column for column in columns if column["name"] == "name"][0]
        if name_column and not name_column["nullable"]:
            batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)
        value_column = [column for column in columns if column["name"] == "value"][0]
        if value_column and not value_column["nullable"]:
            batch_op.alter_column("name", existing_type=sa.VARCHAR(), nullable=True)