def _point_model_card_at_space(self, model) -> None:
        """
        Adds a link from a model's model card to the Trackio Space (preferring the `self._static_space_id` if not None).
        Also adds two tags to the model to indicate that it was trained with Trackio:
        - "trackio"
        - "trackio:<space_url>" (this is used to embed the Space in the model's "Training Metrics" tab)
        """
        if self._space_id is None and self._static_space_id is None:
            return

        prev = getattr(model, "model_tags", None) or []
        old_tag = next((t for t in prev if isinstance(t, str) and t.startswith("trackio:https://")), None)
        if old_tag:
            old_url = old_tag.split(":", 1)[1]
            old_comment = self.BADGE_MARKDOWN.format(space_url=old_url)
            cmt = modelcard.AUTOGENERATED_TRAINER_COMMENT or ""
            if old_comment in cmt:
                modelcard.AUTOGENERATED_TRAINER_COMMENT = cmt.replace(old_comment, "")

        preferred_space_id = self._static_space_id or self._space_id
        preferred_url = self.SPACE_URL.format(space_id=preferred_space_id)
        new_tag = f"trackio:{preferred_url}"
        new_comment = self.BADGE_MARKDOWN.format(space_url=preferred_url)

        kept = [t for t in prev if not (isinstance(t, str) and t.startswith("trackio:https://"))]
        for extra in ("trackio", new_tag):
            if extra not in kept:
                kept.append(extra)
        model.model_tags = kept
        c = modelcard.AUTOGENERATED_TRAINER_COMMENT or ""
        modelcard.AUTOGENERATED_TRAINER_COMMENT = new_comment + c