def downgrade() -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)  # type: ignore
    table_names = inspector.get_table_names()
    # ### commands auto generated by Alembic - please adjust! ###
    if "variable" not in table_names:
        return
    columns = [column for column in inspector.get_columns("variable")]
    column_names = [column["name"] for column in columns]
    with op.batch_alter_table("variable", schema=None) as batch_op:
        if "created_at" in column_names:
            created_at_colunmn = next(column for column in columns if column["name"] == "created_at")
            if created_at_colunmn["nullable"] is True:
                batch_op.alter_column(
                    "created_at",
                    existing_type=sa.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=False,
                )