def parse_response(
        self,
        response: str | list[str | int | list[int]] | np.ndarray | torch.Tensor,
        schema: list | dict | None = None,
    ):
        """
        Converts an output string created by generating text from a model into a parsed message dictionary.
        This method is intended for use with chat models, and will read the tokenizer's `response_schema` attribute to
        control parsing, although this can be overridden by passing a `response_schema` argument directly.

        Args:
            response (`str`):
                The output string generated by the model. This can be either a decoded string or list of strings,
                or token IDs as a list/array.
            schema (`Union[list, dict]`, *optional*):
                A response schema that indicates the expected output format and how parsing should be performed.
                If not provided, the tokenizer's `response_schema` attribute will be used.
        """
        batched = (
            (isinstance(response, list) and not isinstance(response[0], int))
            or getattr(response, "ndim", 0) > 1  # For torch/numpy tensors
        )

        if schema is None:
            if getattr(self, "response_schema", None) is None:
                raise AttributeError("This tokenizer does not have a `response_schema` for parsing chat responses!")
            schema = self.response_schema
        if batched:
            if not (isinstance(response, list) and isinstance(response[0], str)):
                response = self.batch_decode(response)
            return [recursive_parse(single_response, schema) for single_response in response]
        else:
            if not isinstance(response, str):
                response = self.decode(response)
            return recursive_parse(response, schema)