def append_stacktrace_summary(node: Node) -> None:
            """
            Append a summary of the stacktrace to the generated code. This is
            useful for debugging.
            """
            nonlocal prev_summary_str

            if node.op not in {"placeholder", "output"}:
                additional_meta_str = ""
                if additional_meta:
                    parts: list[str] = []
                    for key in additional_meta:
                        if key in node.meta:
                            parts.append(f"{key}: {node.meta[key]}")
                    if parts:
                        additional_meta_str = f"# {', '.join(parts)} "

                annotation_str = ""
                annotation = node.meta.get("custom", {})
                annotation_trunc = {}
                if annotation:
                    for key, value in annotation.items():
                        value_str = str(value)
                        if len(value_str) > 40:
                            annotation_trunc[key] = value_str[:40] + "..."
                        else:
                            annotation_trunc[key] = value
                    annotation_str = f" Annotation: {annotation_trunc}"

                stack_trace_str = "No stacktrace found for following nodes"
                if stack_trace := node.stack_trace:
                    if parsed_stack_trace := _parse_stack_trace(stack_trace):
                        stack_trace_str = parsed_stack_trace.get_summary_str()

                maybe_recompute_info = ""
                if hasattr(node, "meta") and node.meta:
                    # recompute tags are generated by torch.compile and put in the joint graph.
                    # These tags are load bearing enough that we want them to show up by default
                    # in tlparse, when you run torch.compile.
                    recompute = node.meta.get("recompute", None)
                    ac_graph_id = node.meta.get("ac_graph_id", None)

                    if recompute is not None and ac_graph_id is not None:
                        maybe_recompute_info = (
                            f" ac_graph_id: {str(ac_graph_id)} - {str(recompute.name)}"
                        )
                    elif recompute is not None:
                        maybe_recompute_info = f" recompute: {str(recompute.name)}"
                    elif ac_graph_id is not None:
                        maybe_recompute_info = f" ac_graph_id: {str(ac_graph_id)}"

                summary_str = f"\n{dim(f'{additional_meta_str}#{annotation_str}{maybe_recompute_info} {stack_trace_str}')}\n"

                if summary_str != prev_summary_str:
                    prev_summary_str = summary_str
                    body.append(summary_str)