def mock_get_device_status(device: Device) -> dict[str, Any]:
    """Mock API device status."""

    if device.get_id() == "aidoo1":
        return {
            API_ACTIVE: False,
            API_ERRORS: [],
            API_MODE: OperationMode.HEATING.value,
            API_MODE_AVAIL: [
                OperationMode.AUTO.value,
                OperationMode.COOLING.value,
                OperationMode.HEATING.value,
                OperationMode.VENTILATION.value,
                OperationMode.DRY.value,
            ],
            API_SP_AIR_AUTO: {API_CELSIUS: 22, API_FAH: 72},
            API_SP_AIR_COOL: {API_CELSIUS: 22, API_FAH: 72},
            API_SP_AIR_HEAT: {API_CELSIUS: 22, API_FAH: 72},
            API_RANGE_MAX_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_SP_MAX_AUTO_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_SP_MAX_COOL_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_SP_MAX_HOT_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_MIN_AIR: {API_CELSIUS: 15, API_FAH: 59},
            API_RANGE_SP_MIN_AUTO_AIR: {API_CELSIUS: 18, API_FAH: 64},
            API_RANGE_SP_MIN_COOL_AIR: {API_CELSIUS: 18, API_FAH: 64},
            API_RANGE_SP_MIN_HOT_AIR: {API_CELSIUS: 16, API_FAH: 61},
            API_POWER: False,
            API_SPEED_CONF: 6,
            API_SPEED_VALUES: [2, 4, 6],
            API_SPEED_TYPE: 0,
            API_IS_CONNECTED: True,
            API_WS_CONNECTED: True,
            API_LOCAL_TEMP: {API_CELSIUS: 21, API_FAH: 70},
            API_WARNINGS: [],
        }
    if device.get_id() == "aidoo_pro":
        return {
            API_ACTIVE: True,
            API_DOUBLE_SET_POINT: True,
            API_ERRORS: [],
            API_MODE: OperationMode.COOLING.value,
            API_MODE_AVAIL: [
                OperationMode.AUTO.value,
                OperationMode.COOLING.value,
                OperationMode.HEATING.value,
                OperationMode.VENTILATION.value,
                OperationMode.DRY.value,
            ],
            API_SP_AIR_AUTO: {API_CELSIUS: 22, API_FAH: 72},
            API_SP_AIR_COOL: {API_CELSIUS: 22, API_FAH: 72},
            API_SP_AIR_HEAT: {API_CELSIUS: 18, API_FAH: 64},
            API_RANGE_MAX_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_SP_MAX_AUTO_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_SP_MAX_COOL_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_SP_MAX_HOT_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_MIN_AIR: {API_CELSIUS: 15, API_FAH: 59},
            API_RANGE_SP_MIN_AUTO_AIR: {API_CELSIUS: 18, API_FAH: 64},
            API_RANGE_SP_MIN_COOL_AIR: {API_CELSIUS: 18, API_FAH: 64},
            API_RANGE_SP_MIN_HOT_AIR: {API_CELSIUS: 16, API_FAH: 61},
            API_POWER: True,
            API_SPEED_CONF: 3,
            API_SPEED_VALUES: [0, 1, 2, 3, 4, 5],
            API_SPEED_TYPE: 0,
            API_IS_CONNECTED: True,
            API_WS_CONNECTED: True,
            API_LOCAL_TEMP: {API_CELSIUS: 20, API_FAH: 68},
            API_WARNINGS: [],
        }
    if device.get_id() == "dhw1":
        return {
            API_ACTIVE: False,
            API_ERRORS: [],
            API_POWER: False,
            API_POWERFUL_MODE: False,
            API_SETPOINT: {API_CELSIUS: 48, API_FAH: 118},
            API_RANGE_SP_MAX_ACS: {API_CELSIUS: 60, API_FAH: 140},
            API_RANGE_SP_MIN_ACS: {API_CELSIUS: 40, API_FAH: 104},
            API_STEP: {API_CELSIUS: 1, API_FAH: 1},
            API_TANK_TEMP: {API_CELSIUS: 45.5, API_FAH: 114},
            API_IS_CONNECTED: True,
            API_WS_CONNECTED: True,
            API_WARNINGS: [],
        }
    if device.get_id() == "system1":
        return {
            API_AQ_MODE_VALUES: ["off", "on", "auto"],
            API_ERRORS: [
                {
                    API_OLD_ID: "error-id",
                },
            ],
            API_MODE: OperationMode.COOLING.value,
            API_MODE_AVAIL: [
                OperationMode.COOLING.value,
                OperationMode.HEATING.value,
                OperationMode.VENTILATION.value,
                OperationMode.DRY.value,
            ],
            API_IS_CONNECTED: True,
            API_WS_CONNECTED: True,
            API_WARNINGS: [],
        }
    if device.get_id() == "zone1":
        return {
            API_ACTIVE: True,
            API_AIR_ACTIVE: True,
            API_AQ_MODE_CONF: "auto",
            API_AQ_MODE_VALUES: ["off", "on", "auto"],
            API_DOUBLE_SET_POINT: False,
            API_HUMIDITY: 30,
            API_MODE: OperationMode.COOLING.value,
            API_MODE_AVAIL: [
                OperationMode.COOLING.value,
                OperationMode.HEATING.value,
                OperationMode.VENTILATION.value,
                OperationMode.DRY.value,
            ],
            API_RAD_ACTIVE: False,
            API_RANGE_MAX_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_SP_MAX_COOL_AIR: {API_FAH: 86, API_CELSIUS: 30},
            API_RANGE_SP_MAX_DRY_AIR: {API_FAH: 86, API_CELSIUS: 30},
            API_RANGE_SP_MAX_EMERHEAT_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_SP_MAX_HOT_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_SP_MAX_STOP_AIR: {API_FAH: 86, API_CELSIUS: 30},
            API_RANGE_SP_MAX_VENT_AIR: {API_FAH: 86, API_CELSIUS: 30},
            API_RANGE_MIN_AIR: {API_CELSIUS: 15, API_FAH: 59},
            API_RANGE_SP_MIN_COOL_AIR: {API_CELSIUS: 18, API_FAH: 64},
            API_RANGE_SP_MIN_DRY_AIR: {API_CELSIUS: 18, API_FAH: 64},
            API_RANGE_SP_MIN_EMERHEAT_AIR: {API_FAH: 59, API_CELSIUS: 15},
            API_RANGE_SP_MIN_HOT_AIR: {API_FAH: 59, API_CELSIUS: 15},
            API_RANGE_SP_MIN_STOP_AIR: {API_FAH: 59, API_CELSIUS: 15},
            API_RANGE_SP_MIN_VENT_AIR: {API_FAH: 59, API_CELSIUS: 15},
            API_SP_AIR_COOL: {API_CELSIUS: 24, API_FAH: 75},
            API_SP_AIR_DRY: {API_CELSIUS: 24, API_FAH: 75},
            API_SP_AIR_HEAT: {API_CELSIUS: 20, API_FAH: 68},
            API_SP_AIR_VENT: {API_CELSIUS: 24, API_FAH: 75},
            API_SP_AIR_STOP: {API_CELSIUS: 24, API_FAH: 75},
            API_POWER: True,
            API_IS_CONNECTED: True,
            API_WS_CONNECTED: True,
            API_LOCAL_TEMP: {API_FAH: 68, API_CELSIUS: 20},
            API_WARNINGS: [],
        }
    if device.get_id() == "zone2":
        return {
            API_ACTIVE: False,
            API_AIR_ACTIVE: False,
            API_AQ_MODE_CONF: "auto",
            API_AQ_MODE_VALUES: ["off", "on", "auto"],
            API_DOUBLE_SET_POINT: False,
            API_HUMIDITY: 24,
            API_MODE: OperationMode.COOLING.value,
            API_MODE_AVAIL: [],
            API_RAD_ACTIVE: False,
            API_RANGE_MAX_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_SP_MAX_COOL_AIR: {API_FAH: 86, API_CELSIUS: 30},
            API_RANGE_SP_MAX_DRY_AIR: {API_FAH: 86, API_CELSIUS: 30},
            API_RANGE_SP_MAX_EMERHEAT_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_SP_MAX_HOT_AIR: {API_CELSIUS: 30, API_FAH: 86},
            API_RANGE_SP_MAX_STOP_AIR: {API_FAH: 86, API_CELSIUS: 30},
            API_RANGE_SP_MAX_VENT_AIR: {API_FAH: 86, API_CELSIUS: 30},
            API_RANGE_MIN_AIR: {API_CELSIUS: 15, API_FAH: 59},
            API_RANGE_SP_MIN_COOL_AIR: {API_CELSIUS: 18, API_FAH: 64},
            API_RANGE_SP_MIN_DRY_AIR: {API_CELSIUS: 18, API_FAH: 64},
            API_RANGE_SP_MIN_EMERHEAT_AIR: {API_FAH: 59, API_CELSIUS: 15},
            API_RANGE_SP_MIN_HOT_AIR: {API_FAH: 59, API_CELSIUS: 15},
            API_RANGE_SP_MIN_STOP_AIR: {API_FAH: 59, API_CELSIUS: 15},
            API_RANGE_SP_MIN_VENT_AIR: {API_FAH: 59, API_CELSIUS: 15},
            API_SP_AIR_COOL: {API_CELSIUS: 24, API_FAH: 75},
            API_SP_AIR_DRY: {API_CELSIUS: 24, API_FAH: 75},
            API_SP_AIR_HEAT: {API_CELSIUS: 20, API_FAH: 68},
            API_SP_AIR_VENT: {API_CELSIUS: 24, API_FAH: 75},
            API_SP_AIR_STOP: {API_CELSIUS: 24, API_FAH: 75},
            API_POWER: False,
            API_IS_CONNECTED: True,
            API_WS_CONNECTED: True,
            API_LOCAL_TEMP: {API_FAH: 77, API_CELSIUS: 25},
            API_WARNINGS: [],
        }
    if device.get_id() == "airqsensor1":
        return {
            API_AQ_ACTIVE: False,
            API_AQ_MODE_CONF: "auto",
            API_AQ_MODE_VALUES: ["off", "on", "auto"],
            API_AQ_PM_1: 3,
            API_AQ_PM_2P5: 4,
            API_AQ_PM_10: 3,
            API_AQ_PRESENT: True,
            API_AQ_QUALITY: "good",
            API_IS_CONNECTED: True,
            API_WS_CONNECTED: True,
        }
    return {}