def __init__(
        self,
        file_path: str | Iterable[str],
        *,
        api_url: str,
        access_token: SecretStr | None = None,
        file_type: FileTypeInput = None,
        use_doc_orientation_classify: bool | None = False,
        use_doc_unwarping: bool | None = False,
        use_layout_detection: bool | None = None,
        use_chart_recognition: bool | None = None,
        use_seal_recognition: bool | None = None,
        use_ocr_for_image_block: bool | None = None,
        layout_threshold: float | dict[int, float] | None = None,
        layout_nms: bool | None = None,
        layout_unclip_ratio: (
            tuple[float, float] | dict[int, tuple[float, float]] | float | None
        ) = None,
        layout_merge_bboxes_mode: str | dict[str, float] | None = None,
        layout_shape_mode: str | None = None,
        prompt_label: str | None = None,
        format_block_content: bool | None = None,
        repetition_penalty: float | None = None,
        temperature: float | None = None,
        top_p: float | None = None,
        min_pixels: int | None = None,
        max_pixels: int | None = None,
        max_new_tokens: int | None = None,
        merge_layout_blocks: bool | None = None,
        markdown_ignore_labels: list[str] | None = None,
        vlm_extra_args: dict[str, Any] | None = None,
        prettify_markdown: bool | None = None,
        show_formula_number: bool | None = None,
        restructure_pages: bool | None = None,
        merge_tables: bool | None = None,
        relevel_titles: bool | None = None,
        visualize: bool | None = None,
        additional_params: dict[str, Any] | None = None,
        timeout: int = 300,
    ) -> None:
        """Initialize the PaddleOCR-VL loader.

        Args:
            file_path: Single path/URL or an iterable of paths/URLs to PDF or
                image files.
            api_url: URL of the PaddleOCR-VL API endpoint.
            access_token: Optional access token as ``SecretStr``. If ``None``, the value
                from the ``PADDLEOCR_ACCESS_TOKEN`` environment variable will be used,
                if present.
            file_type: File type hint. ``"pdf"`` for PDFs, ``"image"`` for images,
                or ``None`` to infer from the file extension.
            use_doc_orientation_classify: Whether to enable document orientation
                classification.
            use_doc_unwarping: Whether to enable document unwarping.
            use_layout_detection: Whether to enable layout detection.
            use_chart_recognition: Whether to enable chart recognition.
            use_seal_recognition: Whether to enable seal recognition.
            use_ocr_for_image_block: Whether to run OCR on image blocks.
            layout_threshold: Layout detection threshold (float or page-specific dict).
            layout_nms: Whether to apply non-maximum suppression for layout detection.
            layout_unclip_ratio: Layout unclip ratio (float, (min, max) tuple, or dict).
            layout_merge_bboxes_mode: Mode for merging layout bounding boxes.
            layout_shape_mode: Layout shape mode.
            prompt_label: Prompt label for the VLM (for example, ``"ocr"`` or
                ``"table"``).
            format_block_content: Whether to format block content.
            repetition_penalty: Repetition penalty for VLM sampling.
            temperature: Temperature for VLM sampling.
            top_p: Top-p sampling value for VLM.
            min_pixels: Minimum number of pixels allowed in preprocessing.
            max_pixels: Maximum number of pixels allowed in preprocessing.
            max_new_tokens: Maximum number of tokens generated by the VLM.
            merge_layout_blocks: Whether to merge layout blocks across columns.
            markdown_ignore_labels: Layout labels to ignore when generating Markdown.
            vlm_extra_args: Additional configuration parameters for the VLM.
            prettify_markdown: Whether to prettify the Markdown output.
            show_formula_number: Whether to include formula numbers in Markdown.
            restructure_pages: Whether to restructure results across pages.
            merge_tables: Whether to merge tables across pages.
            relevel_titles: Whether to relevel titles.
            visualize: Whether to include visualization results.
            additional_params: Additional parameters to pass directly to the API
                (keys are treated as snake_case and converted to camelCase).
            timeout: Request timeout in seconds.
        """
        self._file_paths = (
            file_path
            if isinstance(file_path, Iterable) and not isinstance(file_path, str)
            else [file_path]
        )

        self.api_url = api_url
        self.timeout = timeout

        if access_token is None:
            env_value = os.getenv("PADDLEOCR_ACCESS_TOKEN")
            self.access_token = SecretStr(env_value) if env_value else None
        else:
            self.access_token = access_token

        self.file_type = _normalize_file_type(file_type)

        base_params: dict[str, Any] = {
            "use_doc_orientation_classify": use_doc_orientation_classify,
            "use_doc_unwarping": use_doc_unwarping,
            "use_layout_detection": use_layout_detection,
            "use_chart_recognition": use_chart_recognition,
            "use_seal_recognition": use_seal_recognition,
            "use_ocr_for_image_block": use_ocr_for_image_block,
            "layout_threshold": layout_threshold,
            "layout_nms": layout_nms,
            "layout_unclip_ratio": layout_unclip_ratio,
            "layout_merge_bboxes_mode": layout_merge_bboxes_mode,
            "layout_shape_mode": layout_shape_mode,
            "prompt_label": prompt_label,
            "format_block_content": format_block_content,
            "repetition_penalty": repetition_penalty,
            "temperature": temperature,
            "top_p": top_p,
            "min_pixels": min_pixels,
            "max_pixels": max_pixels,
            "max_new_tokens": max_new_tokens,
            "merge_layout_blocks": merge_layout_blocks,
            "markdown_ignore_labels": markdown_ignore_labels,
            "vlm_extra_args": vlm_extra_args,
            "prettify_markdown": prettify_markdown,
            "show_formula_number": show_formula_number,
            "restructure_pages": restructure_pages,
            "merge_tables": merge_tables,
            "relevel_titles": relevel_titles,
            "visualize": visualize,
        }

        # Convert all known service parameters from snake_case to camelCase.
        service_params = _snake_keys_to_camel(base_params)

        if additional_params:
            for key, value in additional_params.items():
                if value is None:
                    continue
                service_params[key] = value

        self._service_params = service_params