def read(self):
        # Read in the crontab from the system
        if self.cron_file:
            # read the cronfile
            try:
                with open(self.b_cron_file, 'rb') as f:
                    self.n_existing = to_native(f.read(), errors='surrogate_or_strict')
                    self.lines = self.n_existing.splitlines()
            except OSError:
                # cron file does not exist
                return
            except Exception:
                raise CronTabError("Unexpected error:", sys.exc_info()[0])
        else:
            # FIXME: using safely quoted shell for now, but this really should be two non-shell calls instead.
            (rc, out, err) = self.module.run_command(self._read_user_execute(), use_unsafe_shell=True)

            if rc not in (0, 1):  # 1 can mean that there are no jobs.
                raise CronTabError("Unable to read crontab")

            self.n_existing = out

            lines = out.splitlines()
            count = 0
            for l in lines:
                if count > 2 or (not re.match(r'# DO NOT EDIT THIS FILE - edit the master and reinstall.', l) and
                                 not re.match(r'# \(/tmp/.*installed on.*\)', l) and
                                 not re.match(r'# \(.*version.*\)', l)):
                    self.lines.append(l)
                else:
                    pattern = re.escape(l) + '[\r\n]?'
                    self.n_existing = re.sub(pattern, '', self.n_existing, 1)
                count += 1