def tiff_write_meta(image: bytes,  # pylint:disable=too-many-locals
                    data: PNGHeader | dict[str, T.Any] | bytes) -> bytes:
    """Write Faceswap information to a tiff's image_description field.

    Parameters
    ----------
    png
        The bytes encoded tiff file to write header data to
    data
        The data to write to the image-description field. If provided as a dict, then it should be
        a json serializable object, otherwise it should be data encoded as ascii bytes

    Notes
    -----
    This handles a very specific task of adding, and populating, an ImageDescription field in a
    Tiff file generated by OpenCV. For any other use cases it will likely fail
    """
    if isinstance(data, PNGHeader):
        data = data.to_dict()
    if not isinstance(data, bytes):
        data = json.dumps(data, ensure_ascii=True).encode("ascii")

    assert image[:2] == b"II", "Not a supported TIFF file"
    assert struct.unpack("<H", image[2:4])[0] == 42, "Only version 42 Tiff files are supported"
    ptr = struct.unpack("<I", image[4:8])[0]
    rendered = image[:ptr]  # Pack up to IFD

    num_tags = struct.unpack("<H", image[ptr: ptr + 2])[0]
    ptr += 2
    rendered += struct.pack("<H", num_tags + 1)  # Pack new IFD field count
    remainder = image[ptr + num_tags * 12:]  # Hold the data from after the IFD
    assert struct.unpack("<I", remainder[:4])[0] == 0, "Multi-page TIFF files not supported"

    dtypes = {2: "1s", 3: "1H", 4: "1I", 7: '1B'}

    ifd = b""
    insert_idx = -1
    for i in range(num_tags):
        tag = image[ptr + i * 12:ptr + (1 + i) * 12]

        tag_id = struct.unpack("<H", tag[0:2])[0]
        assert tag_id != 270, "Not a supported TIFF file"

        tag_count = struct.unpack("<I", tag[4:8])[0]
        tag_type = dtypes[struct.unpack("<H", tag[2:4])[0]]
        size = tag_count * struct.calcsize(tag_type)

        if insert_idx < 0 and tag_id > 270:
            insert_idx = i  # Log insert location of image description

        if size <= 4:  # value in offset column
            ifd += tag
            continue

        ifd += tag[:8]
        tag_offset = struct.unpack("<I", tag[8:12])[0]
        new_offset = struct.pack("<I", tag_offset + 12)  # Increment by length of new ifd entry
        ifd += new_offset

    end = len(rendered) + len(ifd) + 12 + len(remainder)
    desc = struct.pack("HH", 270, 2)
    desc += struct.pack("II", len(data), end)
    # TODO confirm no extra pages in end of IFD

    rendered += ifd[:insert_idx * 12] + desc + ifd[insert_idx * 12:] + remainder + data
    return rendered