def render(
        self,
        file_type: FileType,
        resource_name: ResourceName,
    ) -> str:
        # Generated outputs (template, schema)
        # templates
        if file_type == FileType.attribute_template:
            return self.render_attribute_template(resource_name)
        elif file_type == FileType.minimal_template:
            return self.render_minimal_template(resource_name)
        elif file_type == FileType.update_without_replacement_template:
            return self.render_update_without_replacement_template(resource_name)
        elif file_type == FileType.autogenerated_template:
            return self.render_autogenerated_template(resource_name)
        # schema
        elif file_type == FileType.schema:
            return json.dumps(self.schema, indent=2)

        template_mapping = {
            FileType.plugin: "plugin_template.py.j2",
            FileType.provider: "provider_template.py.j2",
            FileType.provider_base: "provider_base_template.py.j2",
            FileType.getatt_test: "test_getatt_template.py.j2",
            FileType.integration_test: "test_integration_template.py.j2",
            # FileType.cloudcontrol_test: "test_cloudcontrol_template.py.j2",
            FileType.parity_test: "test_parity_template.py.j2",
        }
        kwargs = {
            "name": resource_name.full_name,  # AWS::SNS::Topic
            "resource": resource_name.provider_name(),  # SNSTopic
            "scaffolding_version": f"v{SCAFFOLDING_VERSION}",
        }
        # TODO: we might want to segregate each provider in its own directory
        # e.g. .../resource_providers/aws_iam_role/test_X.py vs. .../resource_providers/iam/test_X.py
        # add extra parameters
        tests_output_path = root_dir(self.pro).joinpath(
            f"tests/aws/{resource_name.python_compatible_service_name.lower()}/resource_providers/templates"
        )
        match file_type:
            case FileType.getatt_test:
                kwargs["getatt_targets"] = list(self.get_getatt_targets())
                kwargs["service"] = resource_name.service.lower()
                kwargs["resource"] = resource_name.resource.lower()
                kwargs["template_path"] = str(
                    template_path(
                        resource_name, FileType.attribute_template, tests_output_path, pro=self.pro
                    )
                )
            case FileType.provider | FileType.provider_base:
                property_ir = generate_ir_for_type(
                    [self.schema],
                    resource_name.full_name,
                    provider_prefix=resource_name.provider_name(),
                )
                kwargs["provider_properties"] = property_ir
                kwargs["required_properties"] = self.schema.get("required")
                kwargs["create_only_properties"] = self.schema.get("createOnlyProperties")
                kwargs["read_only_properties"] = self.schema.get("readOnlyProperties")
                kwargs["primary_identifier"] = self.schema.get("primaryIdentifier")
                kwargs["create_permissions"] = (
                    self.schema.get("handlers", {}).get("create", {}).get("permissions")
                )
                kwargs["delete_permissions"] = (
                    self.schema.get("handlers", {}).get("delete", {}).get("permissions")
                )
                kwargs["read_permissions"] = (
                    self.schema.get("handlers", {}).get("read", {}).get("permissions")
                )
                kwargs["update_permissions"] = (
                    self.schema.get("handlers", {}).get("update", {}).get("permissions")
                )
                kwargs["list_permissions"] = (
                    self.schema.get("handlers", {}).get("list", {}).get("permissions")
                )
                kwargs["service"] = resource_name.python_compatible_service_name.lower()
                kwargs["lower_resource"] = resource_name.resource.lower()
                kwargs["pro"] = self.pro
            case FileType.plugin:
                kwargs["service"] = resource_name.python_compatible_service_name.lower()
                kwargs["lower_resource"] = resource_name.resource.lower()
                kwargs["pro"] = self.pro
            case FileType.integration_test:
                kwargs["black_box_template_path"] = str(
                    template_path(
                        resource_name, FileType.minimal_template, tests_output_path, pro=self.pro
                    )
                )
                kwargs["update_template_path"] = str(
                    template_path(
                        resource_name,
                        FileType.update_without_replacement_template,
                        tests_output_path,
                        pro=self.pro,
                    )
                )
                kwargs["autogenerated_template_path"] = str(
                    template_path(
                        resource_name,
                        FileType.autogenerated_template,
                        tests_output_path,
                        pro=self.pro,
                    )
                )
            # case FileType.cloudcontrol_test:
            case FileType.parity_test:
                kwargs["parity_test_filename"] = "test_parity.py"
            case _:
                raise NotImplementedError(f"Rendering template of type {file_type}")

        return get_formatted_template_output(
            self.environment, template_mapping[file_type], **kwargs
        )