def simulate_call(service: str, op: str) -> RowEntry:
    """generates a mock request based on the service and operation model and sends it to the API"""
    client = connect_externally_to.get_client(
        service,
        aws_access_key_id="test",
        aws_secret_access_key="test",
        config=botocore.config.Config(
            parameter_validation=False,
            retries={"max_attempts": 0, "total_max_attempts": 1},
            connect_timeout=90,
            read_timeout=120,
            inject_host_prefix=False,
        ),
    )

    service_model = service_models.get(service)
    op_model = service_model.operation_model(op)
    parameters = generate_request(op_model) or {}
    result = _make_api_call(client, service, op, parameters)
    error_msg = result.get("error_message", "")

    if result.get("error_code", "") == "InternalError":
        # some deeper investigation necessary, check for some common errors here and retry
        if service == "apigateway" and "Unexpected HTTP method" in error_msg:
            # moto currently raises exception in some requests, if the http method is not supported, meaning it is not implemented
            result["status_code"] = 501  # reflect that this is not implemented
        elif (
            "localstack.aws.protocol.parser.ProtocolParserError: Unable to parse request (not well-formed (invalid token)"
            in error_msg
        ):
            # parsing errors might be due to invalid parameter values
            # try to re-create params
            logging.debug(
                "ProtocolParserError detected, old parameters used: %s\nre-running request %s.%s with new parameters",
                parameters,
                service,
                op,
            )
            parameters = generate_request(op_model) or {}
            result = _make_api_call(client, service, op, parameters)
        elif "TypeError" in error_msg and "got an unexpected keyword argument" in error_msg:
            # sometimes LocalStack's autogenerated API is not yet up-to-date, which could cause
            # if we see the 'unexpected keyword argument' error, we can re-try after removing the unknown argument
            while match := re.search("got an unexpected keyword argument '(.*)'", error_msg):
                keyword = match.groups()[0]
                # find the corresponding parameter for the unexpected keyword
                if argument := next(
                    (
                        arg
                        for arg in list(parameters.keys())
                        if keyword.replace("_", "") == arg.casefold()
                    ),
                    None,
                ):
                    logging.warning(
                        "Got 'TypeError' with unexpected keyword argument: '%s' for %s.%s. "
                        "Re-trying without keyword ...",
                        keyword,
                        service,
                        op,
                    )
                    # remove the unexpected keyword and try again
                    parameters.pop(argument)
                    result = _make_api_call(client, service, op, parameters)

                    if result.get("error_code", "") != "InternalError":
                        break
                    if argument in parameters:
                        # sometimes the parameter seem to be automatically added again by boto
                        # happened eg for ClientToken in ec2.ProvisionIpamPoolCidr
                        logging.warning(
                            "unexpected keyword '%s' was added to the parameters again for: %s.%s",
                            argument,
                            service,
                            op,
                        )
                        break
                    error_msg = result.get("error_message", "")
                else:
                    # keyword argument not found in the parameters
                    break
    elif result.get("error_code", "") == "UnsupportedOperation" and service == "stepfunctions":
        # the stepfunction lib returns 500 for not implemented + UnsupportedOperation
        result["status_code"] = 501  # reflect that this is not implemented
    if result.get("status_code") in [0, 901, 902, 903]:
        # something went wrong, we do not know exactly what/why - just try again one more time
        logging.debug(
            "Detected invalid status code %i for %s.%s. Re-running request with new parameters",
            result.get("status_code"),
            service,
            op,
        )
        parameters = generate_request(op_model) or {}  # should be generate_parameters I guess
        result = _make_api_call(client, service, op, parameters)
    return result