def _get_overtime_intervals_by_date(self, attendances, version_map):  # TO REMOVE IN MASTER
        """ return all overtime over the attendances (all of the SAME employee)
            as a list of `Intervals` sets with the rule as the recordset
            generated by `timing` rules in self
        """
        attendances.employee_id.ensure_one()
        employee = attendances.employee_id
        if not attendances:
            return [Intervals(keep_distinct=True)]

        # Timing based
        timing_intervals_by_date = defaultdict(list)
        all_timing_overtime_intervals = Intervals(keep_distinct=True)
        for rule in self.filtered(lambda r: r.base_off == 'timing'):
            new_intervals = rule._get1_timing_overtime_intervals(attendances, version_map)
            all_timing_overtime_intervals |= new_intervals
            for start, end, attendance in new_intervals:
                timing_intervals_by_date[attendance.date].append((start, end, rule))
            # timing_intervals_list.append(
            #     Intervals((start, end, (rule, attendance.date)) for (start, end, attendance) in intervals)
            # )
            # timing_intervals_list.append(
            #     _replace_interval_records(new_intervals, rule)
            # )

        # Quantity Based
        periods = self._get_periods()

        work_hours_by = {period: defaultdict(lambda: 0) for period in periods}
        attendances_by = {period: defaultdict(list) for period in periods}
        overtime_hours_by = {period: defaultdict(lambda: 0) for period in periods}
        overtimes_by = {period: defaultdict(list) for period in periods}
        for attendance in attendances:
            for period, key_date in self._get_period_keys(attendance.date).items():
                work_hours_by[period][key_date] += attendance.worked_hours
                attendances_by[period][key_date].append(
                    (attendance.check_in, attendance.check_out, attendance)
                )
        for start, end, attendance in all_timing_overtime_intervals:
            for period, key_date in self._get_period_keys(attendance.date).items():
                overtime_hours_by[period][key_date] += _time_delta_hours(end - start)
                overtimes_by[period][key_date].append((start, end, attendance))

        # list -> Intervals
        for period in periods:
            overtimes_by[period] = defaultdict(
                lambda: Intervals(keep_distinct=True),
                {
                    date: Intervals(ots, keep_distinct=True)
                    for date, ots in overtimes_by[period].items()
                }
            )
            # non overtime attendances
            attendances_by[period] = defaultdict(
                lambda: Intervals(keep_distinct=True),
                {
                    date: Intervals(atts, keep_distinct=True) - overtimes_by[period][date]
                    for date, atts in attendances_by[period].items()
                }
            )

        quantity_intervals_by_date = defaultdict(list)
        for rule in self.filtered(lambda r: r.base_off == 'quantity').sorted(
            lambda r: {p: i for i, p in enumerate(periods)}[r.quantity_period]
        ):
            period = rule.quantity_period
            for date in attendances_by[period]:
                if rule.expected_hours_from_contract:
                    expected_hours = self._get_expected_hours_from_contract(date, version_map[employee][date], period)
                else:
                    expected_hours = rule.expected_hours

                overtime_quantity = work_hours_by[period][date] - expected_hours
                # if overtime_quantity <= -rule.employee_tolerance and rule.undertime: make negative adjustment
                if overtime_quantity <= 0 or overtime_quantity <= rule.employer_tolerance:
                    continue
                if overtime_quantity < overtime_hours_by[period][date]:
                    for start, end, attendance in _last_hours_as_intervals(
                        starting_intervals=overtimes_by[period][date],
                        hours=overtime_quantity,
                    ):
                        quantity_intervals_by_date[attendance.date].append((start, end, rule))
                else:
                    new_intervals = _last_hours_as_intervals(
                        starting_intervals=attendances_by[period][date],
                        hours=overtime_quantity - overtime_hours_by[period][date],
                    )

                    # Uncommenting this changes the logic of how rules for different periods will interact.
                    # Would make it so weekly overtimes try to overlap daily overtimes as much as possible
                    # for outer_period, key_date in self._get_period_keys(date).items():
                    #     overtimes_by[outer_period][key_date] |= new_intervals
                    #     attendances_by[outer_period][key_date] -= new_intervals
                    #     overtime_hours_by[outer_period][key_date] += sum(
                    #         (end - start).seconds / 3600
                    #         for (start, end, _) in new_intervals
                    #     )

                    for start, end, attendance in (
                        new_intervals | overtimes_by[period][date]
                    ):
                        date = attendance[0].date
                        quantity_intervals_by_date[date].append((start, end, rule))
        intervals_by_date = {}
        for date in quantity_intervals_by_date.keys() | timing_intervals_by_date.keys():
            intervals_by_date[date] = _record_overlap_intervals([
                *timing_intervals_by_date[date],
                *quantity_intervals_by_date[date],
            ])
        return intervals_by_date