def _aggregate_base_line_tax_details(self, base_line, grouping_function):
        """ Aggregate the tax details for a single line according a custom grouping function passed as parameter.
        This method is mainly use for EDI to report some data per line. Most of the time, having the amounts grouped
        by tax is not enough because some details should be excluded, aggregated together or just moved into a separated section
        having another grouping key.

        In case the base_line has no tax, the grouping_function is called with an empty tax_data to get the grouping key for the line.

        Don't forget to call '_add_tax_details_in_base_lines' and '_round_base_lines_tax_details' before calling this method.

        [!] Mirror of the same method in account_tax.js.
        PLZ KEEP BOTH METHODS CONSISTENT WITH EACH OTHERS.

        :param base_line:           A base line generated by '_prepare_base_line_for_taxes_computation'.
        :param grouping_function:   A function taking <base_line, tax_data> as parameter and returning anything
                                    that could be used as key in a dictionary.
                                    Note: you must never return None (explanation in the docstring above).
        :return: A mapping <grouping_key, amounts> where:
            grouping_key                is the grouping_key returned by the 'grouping_function' or 'None'.
            amounts                     is a dictionary containing:
                base_amount_currency:           The base amount of this grouping key expressed in foreign currency.
                base_amount:                    The base amount of this grouping key expressed in local currency.
                raw_base_amount_currency:       The base amount of this grouping key expressed in foreign currency before any rounding.
                raw_base_amount:                The base amount of this grouping key expressed in local currency before any rounding.
                target_base_amount_currency:    The same as 'raw_base_amount_currency' but considering the manual amounts.
                target_base_amount:             The same as 'raw_base_amount' but considering the manual amounts.
                tax_amount_currency:            The tax amount of this grouping key expressed in foreign currency.
                tax_amount:                     The tax amount of this grouping key expressed in local currency.
                raw_tax_amount_currency:        The tax amount of this grouping key expressed in foreign currency before any rounding.
                raw_tax_amount:                 The tax amount of this grouping key expressed in local currency before any rounding.
                target_tax_amount_currency:     The same as 'raw_tax_amount_currency' but considering the manual amounts.
                target_tax_amount:              The same as 'raw_tax_amount' but considering the manual amounts.
                total_excluded_currency:        The delta base amount for the base line involved in this grouping key expressed
                                                in foreign currency.
                total_excluded:                 The delta base amount for the base line involved in this grouping key expressed
                                                in local currency.
                raw_total_excluded_currency:    The delta base amount for the base line involved in this grouping key expressed
                                                in foreign currency before any rounding.
                raw_total_excluded:             The delta base amount for the base line involved in this grouping key expressed
                                                in local currency before any rounding.
                target_total_excluded_currency: The same as 'raw_total_excluded_currency' but considering the manual amounts.
                target_total_excluded:          The same as 'raw_total_excluded' but considering the manual amounts.
                taxes_data:                     The subset of base_line['tax_details']['taxes_data'] aggregated under this grouping_key.
        """
        values_per_grouping_key = {}
        tax_details = base_line['tax_details']
        taxes_data = tax_details['taxes_data']
        manual_tax_amounts = base_line['manual_tax_amounts']

        # If there are no taxes, we pass None to the grouping function.
        for tax_data in (taxes_data or [None]):
            current_manual_tax_amounts = manual_tax_amounts and tax_data and manual_tax_amounts.get(str(tax_data['tax'].id)) or {}

            grouping_key = grouping_function(base_line, tax_data)
            if isinstance(grouping_key, dict):
                grouping_key = frozendict(grouping_key)

            # Base amount.
            if grouping_key not in values_per_grouping_key:
                values = values_per_grouping_key[grouping_key] = {
                    'grouping_key': grouping_key,
                    'taxes_data': [],
                }
                for suffix in ('_currency', ''):
                    excluded_rounded_field = f'total_excluded{suffix}'
                    excluded_delta_field = f'delta_{excluded_rounded_field}'
                    excluded_raw_field = f'raw_{excluded_rounded_field}'
                    excluded_target_field = f'target_{excluded_rounded_field}'
                    excluded_manual_field = f'manual_{excluded_rounded_field}'
                    excluded_rounded_amount = tax_details[excluded_rounded_field] + tax_details[excluded_delta_field]
                    excluded_raw_amount = tax_details[excluded_raw_field]
                    values[excluded_rounded_field] = excluded_rounded_amount
                    values[excluded_raw_field] = excluded_raw_amount
                    if base_line[excluded_manual_field] is not None:
                        excluded_target_amount = base_line[excluded_manual_field]
                    elif not suffix and base_line['manual_total_excluded_currency'] is not None:
                        excluded_target_amount = excluded_rounded_amount
                    else:
                        excluded_target_amount = excluded_raw_amount
                    values[excluded_target_field] = excluded_target_amount

                    tax_base_rounded_field = f'base_amount{suffix}'
                    tax_base_raw_field = f'raw_{tax_base_rounded_field}'
                    tax_base_target_field = f'target_{tax_base_rounded_field}'
                    if tax_data:
                        values[tax_base_rounded_field] = tax_data[tax_base_rounded_field]
                        values[tax_base_raw_field] = tax_data[tax_base_raw_field]
                        if tax_base_rounded_field in current_manual_tax_amounts:
                            values[tax_base_target_field] = current_manual_tax_amounts[tax_base_rounded_field]
                        elif not suffix and 'base_amount_currency' in current_manual_tax_amounts:
                            values[tax_base_target_field] = tax_data[tax_base_rounded_field]
                        else:
                            values[tax_base_target_field] = tax_data[tax_base_raw_field]
                    else:
                        values[tax_base_rounded_field] = excluded_rounded_amount
                        values[tax_base_raw_field] = excluded_raw_amount
                        values[tax_base_target_field] = excluded_target_amount

                    tax_rounded_field = f'tax_amount{suffix}'
                    tax_raw_field = f'raw_{tax_rounded_field}'
                    tax_target_field = f'target_{tax_rounded_field}'
                    values[tax_rounded_field] = 0.0
                    values[tax_raw_field] = 0.0
                    values[tax_target_field] = 0.0

            # Tax amount.
            if tax_data:
                reverse_charge_sign = -1 if tax_data['is_reverse_charge'] else 1
                values = values_per_grouping_key[grouping_key]
                for suffix in ('_currency', ''):
                    tax_rounded_field = f'tax_amount{suffix}'
                    tax_raw_field = f'raw_{tax_rounded_field}'
                    tax_target_field = f'target_{tax_rounded_field}'
                    values[tax_rounded_field] += tax_data[tax_rounded_field]
                    values[tax_raw_field] += tax_data[tax_raw_field]
                    if tax_rounded_field in current_manual_tax_amounts:
                        values[tax_target_field] += reverse_charge_sign * current_manual_tax_amounts[tax_rounded_field]
                    elif not suffix and 'tax_amount_currency' in current_manual_tax_amounts:
                        values[tax_target_field] = tax_data[tax_rounded_field]
                    else:
                        values[tax_target_field] += tax_data[tax_raw_field]
                values['taxes_data'].append(tax_data)

        return values_per_grouping_key