def write(self, file_type: FileType, contents: str):
        file_destination = self.destination_files[file_type]
        destination_path = file_destination.parent
        destination_path.mkdir(parents=True, exist_ok=True)

        if file_destination.exists():
            should_overwrite = self.confirm_overwrite(file_destination)
            if not should_overwrite:
                self.console.print(f"Skipping {file_destination}")
                return

        match file_type:
            # provider
            case FileType.provider:
                self.ensure_python_init_files(destination_path)
                self.write_text(contents, file_destination)
                self.console.print(f"Written provider to {file_destination}")
            case FileType.provider_base:
                self.ensure_python_init_files(destination_path)
                self.write_text(contents, file_destination)
                self.console.print(f"Written provider base to {file_destination}")
            case FileType.plugin:
                self.ensure_python_init_files(destination_path)
                self.write_text(contents, file_destination)
                self.console.print(f"Written plugin to {file_destination}")

            # tests
            case FileType.integration_test:
                self.ensure_python_init_files(destination_path)
                self.write_text(contents, file_destination)
                self.console.print(f"Written integration test to {file_destination}")
            case FileType.getatt_test:
                self.write_text(contents, file_destination)
                self.console.print(f"Written getatt tests to {file_destination}")
            # case FileType.cloudcontrol_test:
            #     self.write_text(contents, file_destination)
            #     self.console.print(f"Written cloudcontrol tests to {file_destination}")
            case FileType.parity_test:
                self.write_text(contents, file_destination)
                self.console.print(f"Written parity tests to {file_destination}")

            # templates
            case FileType.attribute_template:
                self.write_text(contents, file_destination)
                self.console.print(f"Written attribute template to {file_destination}")
            case FileType.minimal_template:
                self.write_text(contents, file_destination)
                self.console.print(f"Written minimal template to {file_destination}")
            case FileType.update_without_replacement_template:
                self.write_text(contents, file_destination)
                self.console.print(
                    f"Written update without replacement template to {file_destination}"
                )
            case FileType.autogenerated_template:
                self.write_text(contents, file_destination)
                self.console.print(
                    f"Written autogenerated properties template to {file_destination}"
                )

            # schema
            case FileType.schema:
                self.write_text(contents, file_destination)
                self.console.print(f"Written schema to {file_destination}")
            case _:
                raise NotImplementedError(f"Writing {file_type}")