def _import_attachments(self, invoice, tree):
        """ EXTENDS 'account_edi_common': ATTEMPTS to create a PDF attachment when the XML file doesn't provide one."""
        IrConfigParam = self.env['ir.config_parameter'].sudo()
        disable_pdf_in_xml = str2bool(IrConfigParam.get_param("account_edi_ubl_cii.disable_pdf_in_xml", 'False'))
        additional_docs = super()._import_attachments(invoice, tree)
        if (
            additional_docs or
            invoice.message_main_attachment_id or
            not invoice.is_purchase_document() or
            disable_pdf_in_xml
        ):
            return additional_docs
        try:
            invoices_by_odoo_xmlid = 'account_edi_ubl_cii.action_report_account_invoices_generated_by_odoo'
            if not self.env.ref(invoices_by_odoo_xmlid, raise_if_not_found=False):
                _logger.warning("Missing template while generating substitute PDF attachment for invoice %s", invoice.id)
                return additional_docs
            report_xmlid = invoices_by_odoo_xmlid

            pdf_raw, pdf_extension = self.env['ir.actions.report'] \
                        ._render_qweb_pdf(report_xmlid, res_ids=[invoice.id])

            if pdf_extension != 'pdf':
                return additional_docs

            # add a watermark to the generated pdf
            with io.BytesIO(pdf_raw) as pdf_stream:
                new_pdf_stream = pdf.add_banner(pdf_stream, _('Generated by Odoo'), logo=False)
                pdf_raw = new_pdf_stream.getvalue()
                new_pdf_stream.close()

            invoice_name = invoice.display_name.replace(_('Draft'), '')
            pdf_filename = _('%(invoice_name)s - Generated by Odoo', invoice_name=invoice_name)

            attachment = self.env['ir.attachment'].create({
                'name': pdf_filename + '.pdf',
                'res_id': invoice.id,
                'res_model': 'account.move',
                'raw': pdf_raw,
                'type': 'binary',
                'mimetype': 'application/pdf',
            })
            invoice._message_set_main_attachment_id(attachment, force=True, filter_xml=False)
            return attachment
        except Exception:  # noqa: BLE001
            _logger.exception("Error while generating substitute PDF attachment for invoice %s", invoice.id)
        return additional_docs