def test_exclude_and_validation(self):
        # This Price instance generated by this form is not valid because the
        # quantity field is required, but the form is valid because the field
        # is excluded from the form. This is for backwards compatibility.
        class PriceFormWithoutQuantity(forms.ModelForm):
            class Meta:
                model = Price
                exclude = ("quantity",)

        form = PriceFormWithoutQuantity({"price": "6.00"})
        self.assertTrue(form.is_valid())
        price = form.save(commit=False)
        msg = "{'quantity': ['This field cannot be null.']}"
        with self.assertRaisesMessage(ValidationError, msg):
            price.full_clean()

        # The form should not validate fields that it doesn't contain even if
        # they are specified using 'fields', not 'exclude'.
        class PriceFormWithoutQuantity(forms.ModelForm):
            class Meta:
                model = Price
                fields = ("price",)

        form = PriceFormWithoutQuantity({"price": "6.00"})
        self.assertTrue(form.is_valid())

        # The form should still have an instance of a model that is not
        # complete and not saved into a DB yet.
        self.assertEqual(form.instance.price, Decimal("6.00"))
        self.assertIsNone(form.instance.quantity)
        self.assertIsNone(form.instance.pk)