def save_env_file(
    path: Path,
    settings: dict[str, str],
    categories: list["Category"],
) -> None:
    """Save environment variables to a .env file.

    Organizes settings by category with headers and preserves any
    existing comments or settings not in our category list.

    Args:
        path: Path to the .env file
        settings: Dict mapping variable names to values
        categories: List of categories for organization
    """
    # Ensure parent directory exists
    path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []

    # Header
    lines.append("#" * 80)
    lines.append("### AutoGPT - CONFIGURATION FILE")
    lines.append("#" * 80)
    lines.append("#")
    lines.append("# Generated by `autogpt config`")
    lines.append("#")
    lines.append("#" * 80)
    lines.append("")

    # Track which settings we've written
    written_keys: set[str] = set()

    # Write settings by category
    for category in categories:
        category_settings = []
        for env_var in category.env_vars:
            if env_var in settings and settings[env_var]:
                category_settings.append((env_var, settings[env_var]))
                written_keys.add(env_var)

        # Only write category if it has settings
        if category_settings:
            lines.append("#" * 80)
            lines.append(f"### {category.name.upper()}")
            lines.append("#" * 80)
            lines.append("")

            for key, value in category_settings:
                # Quote values that need it
                if _needs_quoting(value):
                    value = f'"{_escape_value(value)}"'
                lines.append(f"{key}={value}")

            lines.append("")

    # Write any remaining settings not in categories
    remaining = {k: v for k, v in settings.items() if k not in written_keys and v}
    if remaining:
        lines.append("#" * 80)
        lines.append("### OTHER SETTINGS")
        lines.append("#" * 80)
        lines.append("")

        for key, value in sorted(remaining.items()):
            if _needs_quoting(value):
                value = f'"{_escape_value(value)}"'
            lines.append(f"{key}={value}")

        lines.append("")

    # Write to file
    with open(path, "w") as f:
        f.write("\n".join(lines))