def test_exception_error_codes_are_set() -> None:
    assert AuthorizationError("forbidden", error_code="authorization_error").error_code == "authorization_error"
    assert CredentialResolutionError().error_code == "credentials_resolution_error"
    assert ResourceConflictError().error_code == "deployment_conflict"
    assert RateLimitError().error_code == "deployment_rate_limited"
    assert DeploymentTimeoutError().error_code == "deployment_timeout"
    assert ServiceUnavailableError().error_code == "deployment_provider_unavailable"
    assert DeploymentSupportError().error_code == "unsupported_deployment_type"
    assert ResourceNotFoundError().error_code == "resource_not_found"
    assert InvalidDeploymentTypeError().error_code == "invalid_deployment_type"
    assert InvalidContentError().error_code == "unprocessable_content_error"
    assert InvalidDeploymentOperationError().error_code == "invalid_deployment_operation"
    assert AuthSchemeError().error_code == "unsupported_auth_type"
    assert DeploymentNotConfiguredError().error_code == "deployment_not_configured"
    assert OperationNotSupportedError().error_code == "operation_not_supported"