def generate_stats_md(
    github: dict,
    contributors: int,
    traffic: dict,
    pypi: dict,
    docker_pulls: int,
    star_milestones: list[tuple[str, int]],
) -> str:
    """Generate the full stats.md content with embedded HTML/CSS/JS."""

    now = datetime.now()
    updated_date = now.strftime("%B %d, %Y")

    # Prepare data for charts
    # Monthly PyPI downloads
    monthly_labels = list(pypi["monthly"].keys())
    monthly_values = list(pypi["monthly"].values())

    # Get the latest month's downloads
    latest_month_downloads = monthly_values[-1] if monthly_values else 0

    # Compute total PyPI downloads
    total_pypi = pypi["total"]

    # Star milestones — add current stars as final point
    star_dates = [m[0] for m in star_milestones]
    star_counts = [m[1] for m in star_milestones]
    # Append current date + current star count
    current_date = now.strftime("%Y-%m-%d")
    if not star_dates or star_dates[-1] != current_date:
        star_dates.append(current_date)
        star_counts.append(github["stars"])

    # Cumulative downloads (PyPI + Docker over time)
    # Use monthly PyPI data and spread Docker pulls proportionally
    cumulative_labels = monthly_labels[:]
    cumulative_pypi = []
    running = 0
    for v in monthly_values:
        running += v
        cumulative_pypi.append(running)

    # Daily downloads (last ~180 days)
    daily_data = pypi["daily"]
    daily_labels = [d["date"] for d in daily_data]
    daily_values = [d["downloads"] for d in daily_data]

    # Traffic data
    traffic_dates = []
    traffic_views = []
    traffic_uniques = []
    for v in traffic.get("views", []):
        traffic_dates.append(v["date"])
        traffic_views.append(v["count"])
        traffic_uniques.append(v["uniques"])

    # --- Build the page ---
    return f"""---
hide:
  - navigation
  - toc
---

<!-- Generated by scripts/update_stats.py — do not edit manually -->

<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>

<style>
/* Hide the right-hand TOC sidebar and let content use full width */
#toc-sidebar {{
    display: none !important;
}}
.terminal-mkdocs-main-grid {{
    margin-right: auto;
}}
.terminal-mkdocs-main-content {{
    max-width: 100%;
}}

.stats-page {{
    max-width: 1200px;
    margin: 0 auto;
    padding: 1rem 0;
    font-family: inherit;
}}

.stats-header {{
    text-align: center;
    margin-bottom: 2.5rem;
    padding-bottom: 1.5rem;
    border-bottom: 1px solid #3f3f44;
}}

.stats-header img {{
    height: 48px;
    margin-bottom: 0.5rem;
    filter: drop-shadow(0 0 12px rgba(80, 255, 255, 0.3));
}}

.stats-header h1 {{
    font-size: 1.8rem;
    color: #e8e9ed;
    margin: 0.5rem 0 0.25rem;
    letter-spacing: 0.5px;
}}

.stats-header .subtitle {{
    color: #a3abba;
    font-size: 0.95rem;
}}

/* Metric Cards */
.metrics-grid {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem;
    margin-bottom: 2.5rem;
}}

.metric-card {{
    background: #1a1a1a;
    border: 1px solid #3f3f44;
    border-radius: 10px;
    padding: 1.25rem;
    text-align: center;
    transition: all 0.3s ease;
    position: relative;
    overflow: hidden;
}}

.metric-card::before {{
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    height: 3px;
    background: linear-gradient(90deg, #50ffff, #f380f5);
    opacity: 0;
    transition: opacity 0.3s ease;
}}

.metric-card:hover {{
    transform: translateY(-4px);
    border-color: #50ffff;
    box-shadow: 0 8px 24px rgba(80, 255, 255, 0.12);
}}

.metric-card:hover::before {{
    opacity: 1;
}}

.metric-value {{
    font-size: 2rem;
    font-weight: 700;
    color: #50ffff;
    margin: 0.25rem 0;
    line-height: 1.2;
}}

.metric-label {{
    font-size: 0.8rem;
    color: #a3abba;
    text-transform: uppercase;
    letter-spacing: 1px;
}}

.metric-sublabel {{
    font-size: 0.75rem;
    color: #3f3f44;
    margin-top: 0.25rem;
}}

/* Chart Sections */
.chart-section {{
    background: #1a1a1a;
    border: 1px solid #3f3f44;
    border-radius: 10px;
    padding: 1.5rem;
    margin-bottom: 1.5rem;
}}

.chart-section h2 {{
    font-size: 1.1rem;
    color: #e8e9ed;
    margin: 0 0 1rem 0;
    padding-bottom: 0.75rem;
    border-bottom: 1px solid #3f3f44;
}}

.chart-container {{
    position: relative;
    width: 100%;
    height: 350px;
}}

.chart-row {{
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5rem;
    margin-bottom: 1.5rem;
}}

@media (max-width: 768px) {{
    .stats-page {{
        padding: 0.5rem 0.75rem;
    }}
    .stats-header h1 {{
        font-size: 1.4rem;
    }}
    .chart-row {{
        grid-template-columns: 1fr;
    }}
    .metrics-grid {{
        grid-template-columns: repeat(2, 1fr);
        gap: 0.6rem;
    }}
    .metric-card {{
        padding: 0.9rem 0.5rem;
    }}
    .metric-value {{
        font-size: 1.5rem;
    }}
    .metric-label {{
        font-size: 0.7rem;
    }}
    .chart-container {{
        height: 260px;
    }}
    .chart-section {{
        padding: 1rem;
    }}
}}

@media (max-width: 480px) {{
    .metrics-grid {{
        grid-template-columns: 1fr 1fr;
        gap: 0.5rem;
    }}
    .metric-value {{
        font-size: 1.25rem;
    }}
    .metric-label {{
        font-size: 0.65rem;
        letter-spacing: 0.5px;
    }}
    .metric-sublabel {{
        font-size: 0.65rem;
    }}
    .chart-container {{
        height: 220px;
    }}
    .chart-section h2 {{
        font-size: 0.95rem;
    }}
}}

/* Footer */
.stats-footer {{
    text-align: center;
    padding: 1.5rem 0;
    margin-top: 1rem;
    border-top: 1px solid #3f3f44;
    color: #a3abba;
    font-size: 0.8rem;
}}
</style>

<div class="stats-page">

<div class="stats-header">
    <img src="../assets/images/logo.png" alt="Crawl4AI">
    <h1>Growth</h1>
    <div class="subtitle">Community growth & adoption metrics for Crawl4AI</div>
</div>

<!-- Headline Metrics -->
<div class="metrics-grid">
    <div class="metric-card">
        <div class="metric-label">GitHub Stars</div>
        <div class="metric-value">{fmt_number(github['stars'])}</div>
        <div class="metric-sublabel">stargazers</div>
    </div>
    <div class="metric-card">
        <div class="metric-label">Monthly Downloads</div>
        <div class="metric-value">{fmt_short(latest_month_downloads)}</div>
        <div class="metric-sublabel">PyPI · latest month</div>
    </div>
    <div class="metric-card">
        <div class="metric-label">Total Downloads</div>
        <div class="metric-value">{fmt_short(total_pypi)}</div>
        <div class="metric-sublabel">PyPI cumulative</div>
    </div>
    <div class="metric-card">
        <div class="metric-label">Docker Pulls</div>
        <div class="metric-value">{fmt_short(docker_pulls)}</div>
        <div class="metric-sublabel">hub.docker.com</div>
    </div>
    <div class="metric-card">
        <div class="metric-label">Forks / Contributors</div>
        <div class="metric-value">{fmt_number(github['forks'])} <span style="color:#a3abba;font-size:1rem">/</span> {fmt_number(contributors)}</div>
        <div class="metric-sublabel">GitHub</div>
    </div>
</div>

<!-- Chart 1: Monthly PyPI Downloads (bar) -->
<div class="chart-section">
    <h2>PyPI Monthly Downloads</h2>
    <div class="chart-container">
        <canvas id="monthlyChart"></canvas>
    </div>
</div>

<!-- Chart Row: Stars + Cumulative -->
<div class="chart-row">
    <div class="chart-section">
        <h2>GitHub Star Growth</h2>
        <div class="chart-container">
            <canvas id="starsChart"></canvas>
        </div>
    </div>
    <div class="chart-section">
        <h2>Cumulative PyPI Downloads</h2>
        <div class="chart-container">
            <canvas id="cumulativeChart"></canvas>
        </div>
    </div>
</div>

<!-- Chart Row: Daily + Traffic -->
<div class="chart-row">
    <div class="chart-section">
        <h2>Daily Download Trend</h2>
        <div class="chart-container">
            <canvas id="dailyChart"></canvas>
        </div>
    </div>
    <div class="chart-section">
        <h2>GitHub Traffic (14 days)</h2>
        <div class="chart-container">
            <canvas id="trafficChart"></canvas>
        </div>
    </div>
</div>

<div class="stats-footer">
    Updated {updated_date} &middot; Data from GitHub API, PyPI Stats, Docker Hub
</div>

</div>

<script>
// --- Chart.js Global Config ---
Chart.defaults.color = '#a3abba';
Chart.defaults.borderColor = '#3f3f44';
Chart.defaults.font.family = "'dm', Monaco, 'Courier New', monospace";

const CYAN = '#50ffff';
const CYAN_DIM = 'rgba(80,255,255,0.10)';
const CYAN_HOVER = '#0fbbaa';
const PINK = '#f380f5';
const PINK_DIM = 'rgba(243,128,245,0.10)';
const GRID_COLOR = '#3f3f44';
const TOOLTIP_BG = '#1a1a1a';

const tooltipStyle = {{
    backgroundColor: TOOLTIP_BG,
    borderColor: CYAN,
    borderWidth: 1,
    titleColor: '#e8e9ed',
    bodyColor: '#a3abba',
    padding: 10,
    cornerRadius: 6,
    displayColors: false,
}};

const gridStyle = {{ color: GRID_COLOR, drawBorder: false }};
const tickStyle = {{ color: '#a3abba', font: {{ size: 11 }} }};

// --- Data ---
const monthlyLabels = {json.dumps(monthly_labels)};
const monthlyValues = {json.dumps(monthly_values)};

const starDates = {json.dumps(star_dates)};
const starCounts = {json.dumps(star_counts)};

const cumulativeLabels = {json.dumps(cumulative_labels)};
const cumulativePypi = {json.dumps(cumulative_pypi)};

const dailyLabels = {json.dumps(daily_labels)};
const dailyValues = {json.dumps(daily_values)};

const trafficDates = {json.dumps(traffic_dates)};
const trafficViews = {json.dumps(traffic_views)};
const trafficUniques = {json.dumps(traffic_uniques)};

function shortMonth(label) {{
    const parts = label.split('-');
    const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    return months[parseInt(parts[1])-1] + ' ' + parts[0].slice(2);
}}

function shortDate(label) {{
    const parts = label.split('-');
    const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
    return months[parseInt(parts[1])-1] + ' ' + parts[2];
}}

function fmtK(val) {{
    if (val >= 1000000) return (val/1000000).toFixed(1) + 'M';
    if (val >= 1000) return (val/1000).toFixed(0) + 'K';
    return val;
}}

// --- Chart 1: Monthly Downloads (bar) ---
new Chart(document.getElementById('monthlyChart'), {{
    type: 'bar',
    data: {{
        labels: monthlyLabels.map(shortMonth),
        datasets: [{{
            label: 'Downloads',
            data: monthlyValues,
            backgroundColor: CYAN,
            hoverBackgroundColor: CYAN_HOVER,
            borderRadius: 4,
            borderSkipped: false,
        }}]
    }},
    options: {{
        responsive: true,
        maintainAspectRatio: false,
        plugins: {{
            legend: {{ display: false }},
            tooltip: {{ ...tooltipStyle, callbacks: {{ label: ctx => fmtK(ctx.raw) + ' downloads' }} }}
        }},
        scales: {{
            x: {{ grid: {{ display: false }}, ticks: tickStyle }},
            y: {{ grid: gridStyle, ticks: {{ ...tickStyle, callback: fmtK }} }}
        }}
    }}
}});

// --- Chart 2: Star Growth (area) ---
new Chart(document.getElementById('starsChart'), {{
    type: 'line',
    data: {{
        labels: starDates.map(shortMonth),
        datasets: [{{
            label: 'Stars',
            data: starCounts,
            borderColor: CYAN,
            backgroundColor: CYAN_DIM,
            fill: true,
            tension: 0.35,
            pointRadius: 3,
            pointBackgroundColor: CYAN,
            pointHoverRadius: 6,
        }}]
    }},
    options: {{
        responsive: true,
        maintainAspectRatio: false,
        plugins: {{
            legend: {{ display: false }},
            tooltip: {{ ...tooltipStyle, callbacks: {{ label: ctx => fmtK(ctx.raw) + ' stars' }} }}
        }},
        scales: {{
            x: {{ grid: {{ display: false }}, ticks: {{ ...tickStyle, maxTicksLimit: 8 }} }},
            y: {{ grid: gridStyle, ticks: {{ ...tickStyle, callback: fmtK }} }}
        }}
    }}
}});

// --- Chart 3: Cumulative Downloads (area) ---
new Chart(document.getElementById('cumulativeChart'), {{
    type: 'line',
    data: {{
        labels: cumulativeLabels.map(shortMonth),
        datasets: [{{
            label: 'Cumulative PyPI',
            data: cumulativePypi,
            borderColor: PINK,
            backgroundColor: PINK_DIM,
            fill: true,
            tension: 0.35,
            pointRadius: 3,
            pointBackgroundColor: PINK,
            pointHoverRadius: 6,
        }}]
    }},
    options: {{
        responsive: true,
        maintainAspectRatio: false,
        plugins: {{
            legend: {{ display: false }},
            tooltip: {{ ...tooltipStyle, callbacks: {{ label: ctx => fmtK(ctx.raw) + ' total downloads' }} }}
        }},
        scales: {{
            x: {{ grid: {{ display: false }}, ticks: tickStyle }},
            y: {{ grid: gridStyle, ticks: {{ ...tickStyle, callback: fmtK }} }}
        }}
    }}
}});

// --- Chart 4: Daily Downloads (area) ---
(function() {{
    // Sample daily data to avoid overcrowding (show every 7th day)
    const step = Math.max(1, Math.floor(dailyLabels.length / 60));
    const sampledLabels = dailyLabels.filter((_, i) => i % step === 0);
    const sampledValues = dailyValues.filter((_, i) => i % step === 0);

    new Chart(document.getElementById('dailyChart'), {{
        type: 'line',
        data: {{
            labels: sampledLabels.map(shortDate),
            datasets: [{{
                label: 'Daily Downloads',
                data: sampledValues,
                borderColor: CYAN,
                backgroundColor: CYAN_DIM,
                fill: true,
                tension: 0.3,
                pointRadius: 0,
                borderWidth: 1.5,
            }}]
        }},
        options: {{
            responsive: true,
            maintainAspectRatio: false,
            plugins: {{
                legend: {{ display: false }},
                tooltip: {{ ...tooltipStyle, callbacks: {{ label: ctx => fmtK(ctx.raw) + ' downloads' }} }}
            }},
            scales: {{
                x: {{ grid: {{ display: false }}, ticks: {{ ...tickStyle, maxTicksLimit: 8 }} }},
                y: {{ grid: gridStyle, ticks: {{ ...tickStyle, callback: fmtK }}, beginAtZero: true }}
            }}
        }}
    }});
}})();

// --- Chart 5: GitHub Traffic (dual bar) ---
new Chart(document.getElementById('trafficChart'), {{
    type: 'bar',
    data: {{
        labels: trafficDates.map(shortDate),
        datasets: [
            {{
                label: 'Page Views',
                data: trafficViews,
                backgroundColor: CYAN,
                hoverBackgroundColor: CYAN_HOVER,
                borderRadius: 4,
                borderSkipped: false,
            }},
            {{
                label: 'Unique Visitors',
                data: trafficUniques,
                backgroundColor: PINK,
                hoverBackgroundColor: '#d060d0',
                borderRadius: 4,
                borderSkipped: false,
            }}
        ]
    }},
    options: {{
        responsive: true,
        maintainAspectRatio: false,
        plugins: {{
            legend: {{
                labels: {{ color: '#a3abba', boxWidth: 12, padding: 16 }}
            }},
            tooltip: tooltipStyle,
        }},
        scales: {{
            x: {{ grid: {{ display: false }}, ticks: tickStyle }},
            y: {{ grid: gridStyle, ticks: tickStyle }}
        }}
    }}
}});
</script>
"""