def print(self):
        match self.file_type:
            # service code
            case FileType.provider:
                self.printer.print("\n[underline]Provider template[/underline]\n")
                self.printer.print(Syntax(self.contents, "python"))
            case FileType.provider_base:
                self.printer.print("\n[underline]Provider base template[/underline]\n")
                self.printer.print(Syntax(self.contents, "python"))
            case FileType.plugin:
                self.printer.print("\n[underline]Plugin[/underline]\n")
                self.printer.print(Syntax(self.contents, "python"))
            # tests
            case FileType.integration_test:
                self.printer.print("\n[underline]Integration test file[/underline]\n")
                self.printer.print(Syntax(self.contents, "python"))
            case FileType.getatt_test:
                self.printer.print("\n[underline]GetAtt test file[/underline]\n")
                self.printer.print(Syntax(self.contents, "python"))
            # case FileType.cloudcontrol_test:
            #     self.printer.print("\n[underline]CloudControl test[/underline]\n")
            #     self.printer.print(Syntax(self.contents, "python"))
            case FileType.parity_test:
                self.printer.print("\n[underline]Parity test[/underline]\n")
                self.printer.print(Syntax(self.contents, "python"))

            # templates
            case FileType.attribute_template:
                self.printer.print("\n[underline]Attribute Test Template[/underline]\n")
                self.printer.print(Syntax(self.contents, "yaml"))
            case FileType.minimal_template:
                self.printer.print("\n[underline]Minimal template[/underline]\n")
                self.printer.print(Syntax(self.contents, "yaml"))
            case FileType.update_without_replacement_template:
                self.printer.print("\n[underline]Update test template[/underline]\n")
                self.printer.print(Syntax(self.contents, "yaml"))
            case FileType.autogenerated_template:
                self.printer.print("\n[underline]Autogenerated properties template[/underline]\n")
                self.printer.print(Syntax(self.contents, "yaml"))

            # schema
            case FileType.schema:
                self.printer.print("\n[underline]Schema[/underline]\n")
                self.printer.print(Syntax(self.contents, "json"))
            case _:
                raise NotImplementedError(self.file_type)