def _process_mail_values_state(self, mail_values_dict):
        """ When being in mass mailing, avoid sending emails to void or invalid
        emails. For that purpose a processing of generated values allows to
        give a state and a failure type to mail.mail records that will be
        created at sending time.

        :param dict mail_values_dict: as generated by '_prepare_mail_values';

        :return: updated mail_values_dict
        """
        recipients_info = self._get_recipients_data(mail_values_dict)
        blacklist_ids = self._get_blacklist_record_ids(mail_values_dict, recipients_info)
        optout_emails = self._get_optout_emails(mail_values_dict)
        done_emails = self._get_done_emails(mail_values_dict)
        sent_emails_mapping = {}  # distinct emails sent to each address as {email_address: [mail_values]}

        for record_id, mail_values in mail_values_dict.items():
            recipients = recipients_info[record_id]

            # prevent sending to blocked addresses that were included by mistake
            # blacklisted or optout or duplicate -> cancel
            # invalid or missing email -> error if logged, otherwise cancel
            invalid_email_state = self._invalid_email_state()
            if record_id in blacklist_ids:
                mail_values['state'] = 'cancel'
                mail_values['failure_type'] = 'mail_bl'
                # Do not post the mail into the recipient's chatter
                mail_values['is_notification'] = False
            # void or falsy values -> error
            elif not any(recipients['mail_to']):
                mail_values['state'] = invalid_email_state
                mail_values['failure_type'] = 'mail_email_missing'
            elif not any(recipients['mail_to_normalized']):
                mail_values['state'] = invalid_email_state
                mail_values['failure_type'] = 'mail_email_invalid'
            elif optout_emails and all(
                mail_to in optout_emails for mail_to in recipients['mail_to_normalized']
            ):
                mail_values['state'] = 'cancel'
                mail_values['failure_type'] = 'mail_optout'
            elif done_emails and all(
                mail_to in done_emails for mail_to in recipients['mail_to_normalized']
            ):
                mail_values['state'] = 'cancel'
                mail_values['failure_type'] = 'mail_dup'
            elif (len(self.attachment_ids) == len(mail_values.get('attachment_ids', []))
                  and all(mail_to in sent_emails_mapping
                          for mail_to in recipients['mail_to_normalized'])
                  and any(sent_mail.get('subject') == mail_values.get('subject')
                          and sent_mail.get('body') == mail_values.get('body')
                          for mail_to in recipients['mail_to_normalized']
                          for sent_mail in sent_emails_mapping[mail_to])):
                mail_values['state'] = 'cancel'
                mail_values['failure_type'] = 'mail_dup'
            else:
                for mail_to in recipients['mail_to_normalized']:
                    sent_emails_mapping.setdefault(mail_to, []).append(mail_values)

        done_emails += sent_emails_mapping.keys()

        return mail_values_dict