def test_alter_smallint_pk_to_smallautofield_pk(self):
        """
        Should be able to rename an SmallIntegerField(primary_key=True) to
        SmallAutoField(primary_key=True).
        """

        class SmallIntegerPK(Model):
            i = SmallIntegerField(primary_key=True)

            class Meta:
                app_label = "schema"

        with connection.schema_editor() as editor:
            editor.create_model(SmallIntegerPK)
        self.isolated_local_models = [SmallIntegerPK]
        old_field = SmallIntegerPK._meta.get_field("i")
        new_field = SmallAutoField(primary_key=True)
        new_field.model = SmallIntegerPK
        new_field.set_attributes_from_name("i")
        with connection.schema_editor() as editor:
            editor.alter_field(SmallIntegerPK, old_field, new_field, strict=True)

        # A model representing the updated model.
        class IntegerPKToSmallAutoField(Model):
            i = SmallAutoField(primary_key=True)

            class Meta:
                app_label = "schema"
                apps = new_apps
                db_table = SmallIntegerPK._meta.db_table

        # An id (i) is generated by the database.
        obj = IntegerPKToSmallAutoField.objects.create()
        self.assertIsNotNone(obj.i)